// <auto-generated />
using Bank1.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bank1.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20250929163944_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bank1.Models.Account", b =>
                {
                    b.Property<string>("AccountName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AccountName");

                    b.Property<int>("Pincode")
                        .HasColumnType("int")
                        .HasColumnName("Pincode");

                    b.HasKey("AccountName");

                    b.ToTable("tbAccount");
                });

            modelBuilder.Entity("Bank1.Models.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("AccountName");

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("Balance");

                    b.Property<decimal>("Deposit")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("Deposit");

                    b.Property<string>("TransDate")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TransDate");

                    b.Property<decimal>("Withdraw")
                        .HasColumnType("decimal(15,2)")
                        .HasColumnName("Withdraw");

                    b.HasKey("Id");

                    b.ToTable("tbTransaction");
                });
#pragma warning restore 612, 618
        }
    }
}
